created new branch with tasks for new PR
lensman75/codewars pull request #9
Opened 2021-04-08 15:32 UTC by lensman75

New branch with previous done tasks for correct PR.

2021-04-09 19:58 UTC, lensman75 commented
Can't finish logicalCalculator.js
Can't path through tests.

2021-04-10 02:36 UTC, mkl- requested changes

2021-04-10 02:36 UTC, mkl- commented on carYearsDogYears.js
> +    for (let i = 2; i < humanYears; i++) {
You do not need loop here.
`catYears += otherCatyears * (humanYears - 2)`

2021-04-10 02:36 UTC, mkl- commented on carYearsDogYears.js
> +      return catYear, dogYear;
This `return` is not needed.

2021-04-10 02:36 UTC, mkl- commented on countingSheeps.js
> +    if (arrayOfSheep[i] !== true) {
I guess simple `if` is sufficient
```
if(arrayOfSheep[i] === true) {
   count += 1
}
```

2021-04-10 02:36 UTC, mkl- commented on logicalCalculator.js
> +  if (op === 'XOR' && array.length == 1) {
You do not need this check.

2021-04-10 02:36 UTC, mkl- commented on logicalCalculator.js
> +    }, array[0]);
It is incorrect.
You cannot use array[0] as a starting value for XOR operation.
Test:  
` assert.strictEqual(logicalCalc([false, true], "XOR"), true); `

2021-04-10 02:36 UTC, mkl- commented on logicalCalculator.js
> +    }, array[0]);
It is better to use something like
```
array.reduce(function (one, two) {
      return one ^ two;
    });
```

2021-04-10 02:36 UTC, mkl- commented on logicalCalculator.js
> +      return false;
I guess here should be `true`.

2021-04-10 02:36 UTC, mkl- commented on removeExclamationMark.js
> +    if (arr[i] == '!') {
I guess
```
if(arr[i]  !== '!') {
   newArr.push(arr[i]);
}
```
would be simpler

2021-04-13 15:27 UTC, merged